device = "cuda"
use_wandb = true

[dataset]
format = "predefined"
name = "imagenet"
path = "/home/anousias/Documents/Datasets/Imagenet"
transform = "augment"

[dataset.kw]
task = "classification"
weights = []

[dataset.dataloader.train]
batch_size = 128
shuffle = true
num_workers = 8
drop_last = false

[dataset.dataloader.valid]
batch_size = 32
shuffle = false
num_workers = 2
drop_last = false

[train]

[train.lr_scheduler]
epochs = 40
warmup = 5

[train.optim]
lr = 5e-5
weight_decay = 0.02

[train.layers]
freeze = false


[train.teacher.model]
# Configuration for teacher model

[train.teacher.model.params]
params = "pretrained"

[train.teacher.model.params.params_kw]
weights = "IMAGENET1K_V1"
base_model = "vit_b_16"
filter_branch = []

[train.teacher.model.embed]
embed_type = "rgb"
img_size = 224
p_size = 16
channels = 3
use_cls = true
use_dstl = false
use_regs = 0
pe_type = "learnable"

[train.teacher.model.encoder]
mode = "vit"
N = 12
h = 12
d_in = 768
d_hid = 3072
activation = "gelu"
bias = true
attn_type = "self"
norm_type = "layernorm"
dropout = 0.05
dropout_attn = 0.05

[train.teacher.model.task]
num_classes = 1000

[train.model]
# Configuration for student model

[train.model.params]
params = "pretrained"

[train.model.params.params_kw]
weights = "IMAGENET1K_V1"
base_model = "vit_b_16"
filter_branch = ["embed.pos_embedding"]

# If `use_dstl = true` then there should `mode=deit`
[train.model.embed]
embed_type = "rgb"
img_size = 224
p_size = 16
channels = 3
use_cls = true
use_dstl = true
use_regs = 0
pe_type = "haar"

[train.model.encoder]
mode = "vit"
N = 12
h = 12
d_in = 768
d_hid = 3072
activation = "relu"
bias = false
attn_type = "linear"
norm_type = "rms_norm"
dropout = 0.05
dropout_attn = 0.05

[train.model.task]
num_classes = 1000

[train.loss]
loss_type = "ce"
label_smoothing = 0.05

[other.distill]
dstl_type = "soft"

[other.log]
log_sparsity = true

[out]
model_dir = "./.out/models"
model_name = "vit-base-imagenet-distilled"

[wandb]
WANDB_MODE = "online"         # Options: 'online', 'offline' ,'disabled'
name = "vit-base-16-imagenet"

[wandb.init]
project = "sparta-sw"
entity = "anousias-k3y"
