#!/usr/bin/env python3
"""Python host: run the 12-layer ViT encoder on the Kria (xck26) accelerator.

Pipeline:
    input image -> [preprocess stub] -> X (768x197 int8, feature-major)
    for L in 0..11:  X = encoder_layer_top(X, weights[L], scales[L])   (on FPGA)
    Y -> [postprocess stub] -> logits

Division of labour (all Python; PYNQ is the only hardware dependency):
  - SPARTALoader.Loader   : parse model.bin / manifest -> numpy views.
  - this file (Python)    : allocate + fill DDR buffers (PYNQ), the 12-layer loop,
                            ping-pong activations, pre/post.
  - HwKernel (this file)  : the ONE hardware seam — programs the PL from the .bit
                            and invokes encoder_layer_top by writing the PHYSICAL
                            DDR ADDRESSES of those buffers into its s_axi_control
                            registers, then polling ap_done.

FLOW: this is the custom block-design path, NOT the XRT/Vitis path.  The BD in
scripts/encoder_layer_kr260_bd.tcl emits a .bit/.hwh pair (loadable by PYNQ or
xmutil), never an .xclbin, so there is no XRT kernel to bind arguments to --
the arguments ARE control registers, written directly.  Register offsets come
from the HLS-generated xencoder_layer_top_hw.h; see REGMAP below.

Requires: pynq (on-device) and numpy.  pynq is imported lazily so this file can
be linted/inspected on the dev host without it present.

BRING-UP: on a new bitstream, check the control path before anything else --
    sudo python3 SPARTA.py -b enc_system_wrapper.bit --selftest
which write/read-backs every argument register without touching DDR or starting
the kernel.  If that fails, no datapath debugging is worth doing yet.
"""

from __future__ import annotations

import argparse
import ctypes
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from SPARTALoader import Loader

# Encoder dims (config/inc/encoder_layer_cfg.h).  ENC_N=50 on the 32x32-patch
# baseline: a 7x7 patch grid + 1 CLS token (was 197 on the 16x16-patch model).
ENC_D = 768          # feature width           (ENC_D)
ENC_N = 50           # tokens                  (ENC_MAX_BATCH)
ACT_ELEMS = ENC_D * ENC_N   # feature-major int8 activation buffer size

# Q'/K' DDR scratch, allocated once and reused across all 12 layers.
# MHA_MAX_QK_NNZ (config/inc/mha_cfg.h) = MHA_D * MHA_N_TOKENS = 768*50, i.e.
# the full dense grid -- overflow-proof at any sparsity rather than an assumed
# density.  q_col/k_col are T_MhaHeadIndex (8-bit) on this baseline.
MHA_MAX_QK_NNZ = 38400


# ============================================================================
# The kernel's argument set.  Every buffer field is a physical DDR address
# (uint64); the three dimensions are int32.
#
# Retained as a ctypes.Structure purely as a typed carrier: field NAMES are now
# what matters, since HwKernel looks each one up in REGMAP and writes it to its
# own address.  Field ORDER is no longer load-bearing -- the AXI-Lite map is
# addressed, not positional, which removes the silent mis-binding hazard the
# XRT set_arg path had.  Adding a kernel argument means adding it BOTH here and
# in REGMAP.
#
# Not present (removed with the 32x32-patch / on-chip-H baseline): gamma_mha,
# gamma_mlp, s_q_row/s_k_row/s_v_row/s_o_row/s1_row/s2_row (folded into
# `scales`), and the DDR h_val/h_col/h_ptr CSR (H now streams on-chip through
# the MLP's DATAFLOW region).  SPARTALoader still exposes gammas/scale_rows
# from model.bin -- they are simply no longer kernel arguments.
# ============================================================================
class SpartaLayerArgs(ctypes.Structure):
    _fields_ = [
        ("input", ctypes.c_uint64),
        ("feature_dim", ctypes.c_int32),
        ("tokens_dim", ctypes.c_int32),
        ("intermediate_dim", ctypes.c_int32),
        ("wq_values", ctypes.c_uint64), ("wq_col_idx", ctypes.c_uint64), ("wq_row_ptr", ctypes.c_uint64),
        ("wk_values", ctypes.c_uint64), ("wk_col_idx", ctypes.c_uint64), ("wk_row_ptr", ctypes.c_uint64),
        ("wv_values", ctypes.c_uint64), ("wv_col_idx", ctypes.c_uint64), ("wv_row_ptr", ctypes.c_uint64),
        ("wo_values", ctypes.c_uint64), ("wo_col_idx", ctypes.c_uint64), ("wo_row_ptr", ctypes.c_uint64),
        ("w1_values", ctypes.c_uint64), ("w1_col_idx", ctypes.c_uint64), ("w1_row_ptr", ctypes.c_uint64),
        ("w2_values", ctypes.c_uint64), ("w2_col_idx", ctypes.c_uint64), ("w2_row_ptr", ctypes.c_uint64),
        ("scales", ctypes.c_uint64),
        ("q_val", ctypes.c_uint64), ("q_col", ctypes.c_uint64),
        ("k_val", ctypes.c_uint64), ("k_col", ctypes.c_uint64),
        ("hidden", ctypes.c_uint64), ("output", ctypes.c_uint64),
    ]


# ============================================================================
# s_axi_control register map  (xencoder_layer_top_hw.h, generated by Vitis HLS
# alongside the IP; confirmed against the on-board enc_system_wrapper.hwh).
#
# Two register widths, and they are NOT interchangeable:
#   - the three dimension scalars are 32-bit  -> ONE write
#   - every pointer is 64-bit                 -> TWO writes, low word first
# Writing a pointer as a single 32-bit store leaves the high word holding
# whatever the previous layer put there; on a board with >4GB visible that
# aims the kernel at an arbitrary physical address rather than faulting.
# ============================================================================
AP_CTRL = 0x000          # control/status register
AP_START    = 0x1        # bit0  W/COH -- kernel clears it when it accepts
AP_DONE     = 0x2        # bit1  R     -- LATCHED until ap_continue (see invoke)
AP_IDLE     = 0x4        # bit2  R
AP_READY    = 0x8        # bit3  R/COR
AP_CONTINUE = 0x10       # bit4  W/SC  -- releases the latched done state

# name -> (offset, is_64bit).  Order is documentation only: the AXI-Lite map is
# addressed, not positional, so unlike the XRT set_arg path a misordered entry
# here cannot silently shift the other arguments.
REGMAP = {
    "input":            (0x010, True),
    "feature_dim":      (0x01c, False),
    "tokens_dim":       (0x024, False),
    "intermediate_dim": (0x02c, False),
    "wq_values": (0x034, True), "wq_col_idx": (0x040, True), "wq_row_ptr": (0x04c, True),
    "wk_values": (0x058, True), "wk_col_idx": (0x064, True), "wk_row_ptr": (0x070, True),
    "wv_values": (0x07c, True), "wv_col_idx": (0x088, True), "wv_row_ptr": (0x094, True),
    "wo_values": (0x0a0, True), "wo_col_idx": (0x0ac, True), "wo_row_ptr": (0x0b8, True),
    "w1_values": (0x0c4, True), "w1_col_idx": (0x0d0, True), "w1_row_ptr": (0x0dc, True),
    "w2_values": (0x0e8, True), "w2_col_idx": (0x0f4, True), "w2_row_ptr": (0x100, True),
    "scales":    (0x10c, True),
    "q_val":     (0x118, True), "q_col":      (0x124, True),
    "k_val":     (0x130, True), "k_col":      (0x13c, True),
    "hidden":    (0x148, True),
    "output":    (0x154, True),
}


def _cma_total_bytes(default=1 << 30):
    """Size of the CMA pool, for the PS-DDR bank descriptor.

    Only used as the bank's declared size; allocation still fails normally if
    CMA runs out.  /proc/meminfo reports it in kB."""
    try:
        for line in open("/proc/meminfo"):
            if line.startswith("CmaTotal:"):
                return int(line.split()[1]) * 1024
    except OSError:
        pass
    return default


class HwKernel:
    """encoder_layer_top over PYNQ: programs the PL and invokes via AXI-Lite.

    Replaces the libsparta.so/XRT seam.  The custom block design (see
    scripts/encoder_layer_kr260_bd.tcl) produces a .bit/.hwh pair, not an
    .xclbin, so there is no XRT kernel object to bind arguments to -- the
    arguments ARE the control registers, written directly.
    """

    # s_axi_control base address, from the BD's address map (confirmed in
    # enc_system_wrapper.hwh: BASEVALUE 0x80000000, HIGHVALUE 0x8000FFFF, via
    # M_AXI_HPM0_LPD).  Only used when attaching to an already-programmed PL;
    # with an Overlay the address comes from the metadata instead.
    CONTROL_BASE = 0x8000_0000
    CONTROL_SIZE = 0x1_0000

    def __init__(self, bitstream=None, instance=None, download=True,
                 timeout_s=60.0, base_addr=None):
        self.timeout_s = timeout_s
        self.overlay = None

        if download:
            # Program the PL and let PYNQ resolve the IP from the metadata.
            from pynq import Overlay
            self.overlay = Overlay(bitstream, download=True)
            self.ip = self._find_ip(instance)
        else:
            # Attach to a PL programmed elsewhere (xmutil).  Deliberately does
            # NOT build an Overlay: that would parse the .hwh, and PYNQ 3.0.1's
            # pynqmetadata (0.1.2) cannot read a Vivado 2025.2 .hwh
            # ("Unknown file format").  Nothing here needs the metadata -- the
            # control base is fixed by the block design and the register
            # offsets come from REGMAP -- so map the register block directly.
            from pynq import MMIO
            self.ip = MMIO(base_addr or self.CONTROL_BASE, self.CONTROL_SIZE)
            self._register_ps_memory()

    @staticmethod
    def _register_ps_memory():
        """Give PYNQ a PS-DDR memory bank so pynq.allocate() works.

        allocate() -> Device.allocate() -> Device.default_memory, and on the
        embedded device default_memory is derived from an overlay's mem_dict
        (or a global-state file written when PYNQ downloads a bitstream).
        Attaching to an xmutil-loaded PL leaves both absent, so allocate()
        dies with "Overlay is not downloaded" even though CMA is perfectly
        usable.

        default_memory picks the mem_dict entry whose base_address is 0, so
        publishing a single PS-DDR descriptor there restores the normal path.
        The buffers still come from PYNQ's CMA allocator -- this only tells
        PYNQ which bank to use, it does not bypass it.  That matters: the
        kernel's m_axi masters DMA to physical addresses with no IOMMU, so the
        buffers must stay contiguous and CMA-backed.
        """
        from pynq.pl_server import Device

        dev = Device.active_device
        if getattr(dev, "mem_dict", None):
            return                              # already populated
        # XrtMemory reads exactly these three keys; idx is the memory-bank
        # index handed to the allocator, and 0 is the PS-DDR bank.
        dev.mem_dict = {
            "PSDDR": {
                "idx": 0,
                "base_address": 0,
                "size": _cma_total_bytes(),
                "type": "PSDDR",
                "streaming": False,
            }
        }

    def _find_ip(self, instance):
        """Resolve the kernel's IP handle, by name or by scanning the overlay.

        The BD names the cell (enc_top_0 in the current design), so the name is
        not guessable from the kernel name -- discovery matches on the HLS VLNV
        instead, which survives a BD rename."""
        if instance is not None:
            return getattr(self.overlay, instance)

        matches = [n for n, d in self.overlay.ip_dict.items()
                   if "encoder_layer_top" in d.get("type", "")]
        if not matches:
            raise RuntimeError(
                "no encoder_layer_top IP in this overlay; found: "
                f"{sorted(self.overlay.ip_dict)}.  Pass instance=... explicitly.")
        if len(matches) > 1:
            raise RuntimeError(f"ambiguous encoder_layer_top instances: {matches}")
        return getattr(self.overlay, matches[0].split("/")[-1])

    def _write_arg(self, name, value):
        off, is64 = REGMAP[name]
        if is64:
            self.ip.write(off,     value        & 0xFFFFFFFF)
            self.ip.write(off + 4, (value >> 32) & 0xFFFFFFFF)
        else:
            self.ip.write(off, value & 0xFFFFFFFF)

    def read_arg(self, name):
        """Read one argument register back (all data registers are Read/Write)."""
        off, is64 = REGMAP[name]
        lo = self.ip.read(off)
        return (self.ip.read(off + 4) << 32 | lo) if is64 else lo

    def selftest(self, verbose=True):
        """Write/read-back every argument register; return list of failures.

        This checks ONE thing: that the PS can address the kernel's AXI-Lite
        control interface correctly.  It does not start the kernel and needs no
        DDR buffers, so it cleanly separates a control-path problem from a
        datapath one -- run it first on any new bitstream.

        The patterns are chosen to catch the failure modes this board has
        actually produced, not just stuck bits:
          - 0xA5A5A5A5 / 0x5A5A5A5A : alternating bits, catches stuck/shorted
            data lines and a byte lane that is not being driven.
          - 0xFFFFFFFF / 0x00000000 : all-ones then all-zeros, catches a lane
            stuck in one direction only.
          - a per-register unique value : catches ADDRESS aliasing -- two
            registers that decode to the same location still pass every
            uniform pattern, because each one reads back the value it just
            wrote.  This is the pattern that catches the GP0 width-converter
            bug (writes to non-16-byte-aligned offsets silently dropped),
            which uniform patterns alone can miss.
        """
        failures = []

        def check(name, off, wrote, got, note):
            if wrote != got:
                failures.append(
                    f"{name}@0x{off:03x} {note}: wrote 0x{wrote:08x}, "
                    f"read 0x{got:08x}")

        # Per-32-bit-word view: a 64-bit arg is two independently addressed
        # words, and only testing the pair together would hide a dead high word.
        words = []
        for name, (off, is64) in REGMAP.items():
            words.append((f"{name}.lo" if is64 else name, off))
            if is64:
                words.append((f"{name}.hi", off + 4))

        for pattern in (0xA5A5A5A5, 0x5A5A5A5A, 0xFFFFFFFF, 0x00000000):
            for name, off in words:
                self.ip.write(off, pattern)
            for name, off in words:
                check(name, off, pattern, self.ip.read(off), f"pattern 0x{pattern:08x}")

        # Address-aliasing pass: every word gets a DIFFERENT value, all written
        # before any is read back, so an aliased pair shows up as one clobbering
        # the other.
        unique = {off: (0xC0DE0000 | (i * 4)) for i, (_, off) in enumerate(words)}
        for _, off in words:
            self.ip.write(off, unique[off])
        for name, off in words:
            check(name, off, unique[off], self.ip.read(off), "unique/aliasing")

        # Leave the control registers zeroed rather than full of test junk: a
        # later ap_start must not inherit a stale pointer from the selftest.
        for _, off in words:
            self.ip.write(off, 0)

        if verbose:
            ctrl = self.ip.read(AP_CTRL)
            print(f"control base : {self._base_addr_str()}")
            print(f"ap_ctrl      : 0x{ctrl:08x} "
                  f"(start={bool(ctrl & AP_START)}, done={bool(ctrl & AP_DONE)}, "
                  f"idle={bool(ctrl & AP_IDLE)}, ready={bool(ctrl & AP_READY)})")
            if ctrl & AP_DONE:
                print("               ^ done is LATCHED from an earlier run "
                      "(ap_ctrl_chain); invoke() clears it before starting.")
            print(f"registers    : {len(words)} 32-bit words "
                  f"({len(REGMAP)} kernel arguments)")
            print(f"patterns     : 5 (4 uniform + 1 unique/aliasing)")
            if failures:
                print(f"\nFAIL -- {len(failures)} register(s) did not read back:")
                for f in failures:
                    print(f"  {f}")
            else:
                print("\nPASS -- every argument register read back correctly.")
        return failures

    def _base_addr_str(self):
        """The IP's control base, for selftest output (best-effort).

        An Overlay-resolved IP keeps its MMIO in .mmio; a directly-mapped one
        (the attach path) IS the MMIO."""
        for obj in (getattr(self.ip, "mmio", None), self.ip):
            addr = getattr(obj, "base_addr", None)
            if addr is not None:
                return f"0x{addr:08x}"
        return "unknown"

    def invoke(self, args):
        """Write all 29 arguments, start the kernel, block until it completes.

        `args` is a SpartaLayerArgs -- kept as the argument-carrying type so the
        buffer-address plumbing is shared with the XRT path it replaces.

        This block is ap_ctrl_chain, NOT ap_ctrl_hs (confirmed in the generated
        encoder_layer_top_control_s_axi.v: "bit 4 - ap_continue", and
        int_task_ap_done <= task_ap_done && !int_ap_continue).  So ap_done
        LATCHES after each run and the kernel refuses further starts until
        ap_continue is written.  Handshake per invocation:

            1. drain a latched ap_done from the previous run (ap_continue)
            2. wait for ap_idle -- proof the kernel really is ready
            3. write ap_start
            4. wait for ap_done
            5. write ap_continue to release the done state

        Skipping step 1/5 is not a slow failure but a SILENT one: ap_done reads
        as already-set, the wait falls straight through, and the caller gets an
        untouched output buffer that looks like a successful 1ms run."""
        import time

        # ---- 1+2: make sure the kernel is idle and not parked in done -------
        self._drain_done()

        for name in REGMAP:
            self._write_arg(name, getattr(args, name))

        # ---- 3: start ------------------------------------------------------
        # _drain_done() guarantees ap_done is clear here, so the ap_done seen
        # below can only come from THIS run.
        self.ip.write(AP_CTRL, AP_START)
        t_start = time.monotonic()

        # ---- 4: wait for completion ---------------------------------------
        deadline = t_start + self.timeout_s
        while True:
            ctrl = self.ip.read(AP_CTRL)
            if ctrl & AP_DONE:
                break
            if time.monotonic() > deadline:
                raise TimeoutError(
                    f"encoder_layer_top did not assert ap_done within "
                    f"{self.timeout_s}s (ap_ctrl=0x{ctrl:08x}, "
                    f"start={bool(ctrl & AP_START)}, idle={bool(ctrl & AP_IDLE)}). "
                    "A hung kernel usually means a bad buffer address or an "
                    "m_axi bundle that does not reach a PS port.")

        # ---- 5: release the done state so the next invoke can start --------
        self.ip.write(AP_CTRL, AP_CONTINUE)
        return time.monotonic() - t_start

    def _drain_done(self):
        """Clear a latched ap_done and wait until the kernel reports idle.

        On ap_ctrl_chain the done state persists across invocations, so this
        runs BEFORE every start rather than only at init -- an aborted run
        (Ctrl-C, an exception between start and continue) would otherwise leave
        the block latched for the next process to trip over."""
        import time

        deadline = time.monotonic() + self.timeout_s
        while True:
            ctrl = self.ip.read(AP_CTRL)
            # Ready to start only when idle AND no completion still latched.
            # Checking idle alone is not enough: the block reports
            # idle|done (0x6) while parked on an unacknowledged completion,
            # and starting from there leaves ap_done set so the next wait
            # falls straight through -- a silent no-op run.
            if (ctrl & AP_IDLE) and not (ctrl & AP_DONE):
                return
            if ctrl & AP_DONE:
                self.ip.write(AP_CTRL, AP_CONTINUE)
            if time.monotonic() > deadline:
                raise TimeoutError(
                    f"encoder_layer_top is not startable (ap_ctrl=0x{ctrl:08x}, "
                    f"done={bool(ctrl & AP_DONE)}, idle={bool(ctrl & AP_IDLE)}). "
                    "If done stays latched despite ap_continue, or the block "
                    "never goes idle, reload the PL (xmutil) to reset it.")

    def close(self):
        pass    # the Overlay owns the PL; nothing per-kernel to release.


# ============================================================================
# pre / post processing  (STUBS — fill in with the real image pipeline)
# ============================================================================
def preprocess(image) -> np.ndarray:
    """image -> X : (ENC_D*ENC_N,) int8 feature-major activations for layer 0.

    STUB.  The real path is: patch-embed + cls token + pos-embed + the input
    quantizer (quant_input scale) that turns the embedded tokens into int8.
    Returns zeros of the right shape/type so the plumbing runs end-to-end.
    """
    return np.zeros(ACT_ELEMS, dtype=np.int8)


def postprocess(y: np.ndarray):
    """Y (final encoder output, int8 feature-major) -> logits / class.

    STUB.  The real path is: take the cls-token row, layernorm + classifier head
    (dequant with the head scales), argmax -> CIFAR-10 class.
    """
    return None


# ============================================================================
# device buffers / kernel
# ============================================================================
def _allocate(pynq_allocate, nbytes, dtype=np.uint8):
    """Contiguous, cache-coherent DDR buffer (pynq.allocate wrapper)."""
    return pynq_allocate(shape=(nbytes,), dtype=dtype)


def _stage_layer(alloc, layer):
    """Copy one layer's payload blobs into fresh PYNQ DDR buffers and sync to card.
    Returns a dict of named device buffers used to wire the kernel args."""
    bufs = {}

    def stage(name, arr):
        b = _allocate(alloc, arr.nbytes, np.uint8)
        b[:] = np.frombuffer(np.ascontiguousarray(arr).tobytes(), dtype=np.uint8)
        b.sync_to_device()
        bufs[name] = b

    for tag, w in layer.weights.items():
        stage(f"{tag}.values", w.values)
        stage(f"{tag}.col",    w.col)
        stage(f"{tag}.rowptr", w.rowptr)
    stage("scales", layer.scales)
    # NOT staged: scale_rows and gammas.  Neither is a kernel argument on this
    # baseline -- the per-row requant folded into `scales` and the gammas into
    # the datapath.  SPARTALoader still exposes them (older manifests carry
    # them), but copying them to DDR would cost a buffer each, per layer, for
    # data the kernel never reads.
    return bufs


def _addr(buf):
    """Physical DDR address of a PYNQ buffer (what the C invoke ABI wants)."""
    return int(buf.device_address)


def _build_args(x_buf, h_buf, y_buf, lb, scratch, n_tokens, d, d_h):
    """Fill a SpartaLayerArgs from PYNQ buffer device addresses.

    Field order matches encoder_layer_top()'s signature.  The weight tag names
    (`w_q.values`, `out_proj.rowptr`, ...) come from compile_model.py's
    manifest via SPARTALoader and are unaffected by the runtime flow."""
    return SpartaLayerArgs(
        input=_addr(x_buf),
        feature_dim=d, tokens_dim=n_tokens, intermediate_dim=d_h,
        wq_values=_addr(lb["w_q.values"]), wq_col_idx=_addr(lb["w_q.col"]), wq_row_ptr=_addr(lb["w_q.rowptr"]),
        wk_values=_addr(lb["w_k.values"]), wk_col_idx=_addr(lb["w_k.col"]), wk_row_ptr=_addr(lb["w_k.rowptr"]),
        wv_values=_addr(lb["w_v.values"]), wv_col_idx=_addr(lb["w_v.col"]), wv_row_ptr=_addr(lb["w_v.rowptr"]),
        wo_values=_addr(lb["out_proj.values"]), wo_col_idx=_addr(lb["out_proj.col"]), wo_row_ptr=_addr(lb["out_proj.rowptr"]),
        w1_values=_addr(lb["linear_1.values"]), w1_col_idx=_addr(lb["linear_1.col"]), w1_row_ptr=_addr(lb["linear_1.rowptr"]),
        w2_values=_addr(lb["linear_2.values"]), w2_col_idx=_addr(lb["linear_2.col"]), w2_row_ptr=_addr(lb["linear_2.rowptr"]),
        scales=_addr(lb["scales"]),
        q_val=_addr(scratch["q_val"]), q_col=_addr(scratch["q_col"]),
        k_val=_addr(scratch["k_val"]), k_col=_addr(scratch["k_col"]),
        hidden=_addr(h_buf), output=_addr(y_buf),
    )


def run_encoder(model_dir, image=None, bitstream=None, instance=None,
                download=True, base_addr=None):
    """Load payload, run the 12 encoder layers on the FPGA, return postprocess(Y).

    Python allocates/fills all DDR buffers (PYNQ) and drives the loop; HwKernel
    performs each kernel invocation over AXI-Lite."""
    from pynq import allocate            # on-device only; import lazily.

    mp = Loader(model_dir)
    layers = mp.layer_indices()

    kernel = HwKernel(bitstream, instance=instance, download=download,
                      base_addr=base_addr)

    # activation ping-pong: X (in) / Y (out) / hidden (MHA->MLP handoff).
    a = _allocate(allocate, ACT_ELEMS, np.int8)
    b = _allocate(allocate, ACT_ELEMS, np.int8)
    h = _allocate(allocate, ACT_ELEMS, np.int8)

    # Q'/K' scratch: written and read entirely by the kernel, never by the
    # host, so it is allocated once and reused across all 12 layers rather
    # than re-staged per layer.
    scratch = {
        "q_val": _allocate(allocate, MHA_MAX_QK_NNZ, np.int8),
        "q_col": _allocate(allocate, MHA_MAX_QK_NNZ, np.uint8),
        "k_val": _allocate(allocate, MHA_MAX_QK_NNZ, np.int8),
        "k_col": _allocate(allocate, MHA_MAX_QK_NNZ, np.uint8),
    }

    # ---- preprocess -> X into buffer `a` ----
    x0 = preprocess(image)
    a[:] = x0
    a.sync_to_device()
    x_buf, y_buf = a, b

    try:
        for L in layers:
            layer = mp.layer(L)
            d_h = layer.weights["linear_1"].shape[0]
            lb = _stage_layer(allocate, layer)
            args = _build_args(x_buf, h, y_buf, lb, scratch, ENC_N, ENC_D, d_h)
            try:
                kernel.invoke(args)
            except TimeoutError as e:
                raise RuntimeError(f"encoder layer {L} hung: {e}") from e
            y_buf.sync_from_device()
            # free this layer's weight buffers before the next (weights
            # dominate DDR; all 12 layers resident at once would not fit).
            for buf in lb.values():
                buf.freebuffer()
            x_buf, y_buf = y_buf, x_buf     # output becomes next input

        # after the loop the last output is in x_buf (post-swap).
        x_buf.sync_from_device()
        y = np.array(x_buf[:ACT_ELEMS], dtype=np.int8)
    finally:
        kernel.close()

    return postprocess(y)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-d", "--model-dir", default=None,
                    help="dir with model.bin + manifest.json (from compile_model.py); "
                         "not needed with --selftest")
    ap.add_argument("-b", "--bitstream", default=None,
                    help="overlay to program (.bit, with its .hwh alongside); "
                         "not needed with --no-download")
    ap.add_argument("--instance", default=None,
                    help="BD cell name of the kernel (default: discover it)")
    ap.add_argument("--no-download", action="store_true",
                    help="attach to a PL already programmed (e.g. by xmutil) "
                         "instead of reprogramming it; maps the control "
                         "registers directly and needs no .bit/.hwh")
    ap.add_argument("--base-addr", default=None,
                    help=f"s_axi_control base address when attaching "
                         f"(default 0x{HwKernel.CONTROL_BASE:08x})")
    ap.add_argument("--selftest", action="store_true",
                    help="write/read-back every control register and exit; "
                         "checks the AXI-Lite control path only (no DDR, no "
                         "ap_start). Run this first on a new bitstream.")
    ap.add_argument("--image", default=None, help="input image (preprocess stub ignores it)")
    args = ap.parse_args()

    if not args.bitstream and not args.no_download:
        ap.error("-b/--bitstream is required unless --no-download is given")
    base = int(args.base_addr, 0) if args.base_addr else None

    if args.selftest:
        kernel = HwKernel(args.bitstream, instance=args.instance,
                          download=not args.no_download, base_addr=base)
        failures = kernel.selftest()
        return 1 if failures else 0

    if not args.model_dir:
        ap.error("-d/--model-dir is required unless --selftest is given")

    result = run_encoder(args.model_dir, image=args.image, bitstream=args.bitstream,
                         instance=args.instance, download=not args.no_download,
                         base_addr=base)
    print(f"encoder done; postprocess -> {result}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
